### Create a club
POST http://localhost:8080/api/clubs/new
Content-Type: application/json

{
  "title": "Programming Club",
  "photoUrl": "https://example.com/photo.jpg",
  "content": "A club for running enthusiasts"
}

### Update a club
PUT http://localhost:8080/api/clubs/2
Content-Type: application/json

{
"title": "",
"photoUrl": "https://example.com/new-photo.jpg",
"content": "Updated description for the club"
}


### Find a club by ID
GET http://localhost:8080/api/clubs/2


### Delete a club by ID
DELETE http://localhost:8080/api/clubs/2/delete

### Search clubs by title
GET http://localhost:8080/api/clubs/search?query=Programming

